# -*- coding: utf-8 -*-
"""Special Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l0quK8dJ8slH24VRjo_iF9zfVjDlgSwZ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import pickle
import re
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.linear_model import SGDClassifier

import nltk
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords

from sklearn.feature_extraction.text import TfidfVectorizer

!pip install xgboost

nltk.download('stopwords')
STOPWORDS = set(stopwords.words('english'))
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
from wordcloud import WordCloud
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier

import pandas as pd
import os

DATASET_PATH = r"c:\Users\nraja\Downloads\SPL project\amazon_reviews.csv"
df = pd.read_csv(DATASET_PATH)
print(f"Dataset shape : {df.shape}")

df.head()

df.isnull().sum

"""reviewCreatedVersion and appVersion containing a large number of null values"""

for i, col in enumerate(df.columns):
    print(i, repr(col))

df.isna().sum()

df[df['content'].isna()]
df[df['userName'].isna()]

df.dropna(inplace=True)

print(f"Dataset shape after dropping null values : {df.shape}")

df['length'] = df['content'].apply(len)

df.head()

df['content'] = df['content'].astype(str)
df['length'] = df['content'].apply(lambda x: len(str(x)))
print(f"content column value : {df['content'].iloc[1]}")
print(f"length of review : {len(df['content'].iloc[1])} ")
print(f"length column value : {df['length'].iloc[1]}")

"""Data Types"""

df.dtypes

"""Analyzing 'score' column"""

len(df)

print(f"score value count: \n{df['score'].value_counts()}")

print(f"Unique values in score column : {df['score'].unique()}")

"""Let's plot the above values in a Bar Graph (for score)"""

df['score'].value_counts().plot.bar(color='blue')
plt.title("score value count")
plt.xlabel("score")
plt.ylabel("count")
plt.show()

"""Pie Chart"""

fig = plt.figure(figsize=(6,6))
colors = ('red','green','blue','yellow','orange')
plt.pie(df['score'].value_counts(),
labels=df['score'].unique(),
colors=colors,
autopct='%.0f%%')

"""Since our feedback in the table is named as content.
Let's analyze count
"""

print(f"content value count: \n{df['content'].value_counts()}")

"""Bar Graph (for content/feedback)"""

import matplotlib as mpl
top_content_counts = df['content'].value_counts().head(10)
mpl.rcParams['text.usetex'] = False
mpl.rcParams['mathtext.default'] = 'regular'
top_content_counts.plot.bar(color='green')
plt.title("Top 10 Content Value Count")
plt.xlabel("Content")
plt.ylabel("Count")
plt.xticks(rotation=90, ha='right')
plt.tight_layout()
plt.show()

"""Pie Chart"""

import matplotlib as mpl
top_content_counts = df['content'].value_counts().head(10)
pie_labels = top_content_counts.index.tolist()
pie_values = top_content_counts.values
mpl.rcParams['text.usetex'] = False
mpl.rcParams['mathtext.default'] = 'regular'
fig = plt.figure(figsize=(10, 10))
colors = ['red', 'green', 'blue', 'yellow', 'orange', 'purple', 'cyan', 'magenta', 'lime', 'pink']
plt.pie(pie_values,
        labels=pie_labels,
        colors=colors[:len(pie_values)],
        autopct='%1.1f%%',
        startangle=90,
        pctdistance=0.85
       )
plt.title("Top 10 Content Value Distribution")
plt.axis('equal')
plt.tight_layout()
plt.show()

"""Let's see the 'score' values for different values of 'content'"""

print("Examining score distribution for the top 5 most frequent content entries:")
top_5_content = df['content'].value_counts().head(5)
for content_text, count in top_5_content.items():
    print(f"--- Content: '{content_text}' (appears {count} times) ---")
    score_distribution = df[df['content'] == content_text]['score'].value_counts().sort_index()
    if not score_distribution.empty:
        print(score_distribution)
    else:
        print("No scores found for this content.")
    print()

"""Calculating mean of score and content"""

import matplotlib as mpl
top_10_content = df['content'].value_counts().head(10).index
df_top_content = df[df['content'].isin(top_10_content)]
mean_scores_top_content = df_top_content.groupby('content')['score'].mean().sort_values()
mpl.rcParams['text.usetex'] = False
mpl.rcParams['mathtext.default'] = 'regular'
mean_scores_top_content.plot.bar(color = 'red', figsize = (12, 6))
plt.title('Mean Score by Top 10 Most Frequent Content')
plt.xlabel('Content')
plt.ylabel('Mean Score')
plt.xticks(rotation=90, ha='right')
plt.tight_layout()
plt.show()

"""Analyzing 'reviewId'"""

df['length'].describe()

"""Length analysis for full dataset"""

sns.histplot(df['length'], kde=True)
plt.title('Distribution of Review Lengths for Reviews with Content')
plt.xlabel('Review Length')
plt.ylabel('Frequency')
plt.show()

"""Length wise mean rating"""

df.groupby('length')['score'].mean().plot.hist(color='blue',figsize = (7,6), bins=20)
plt.title('Review Length by Mean Rating')
plt.xlabel('Mean Rating')
plt.ylabel('Review Length')
plt.show()

"""**Count Vectorizer**"""

cv = CountVectorizer(stop_words='english')
words = cv.fit_transform(df['content'])

content = " ".join([content for content in df['content']])
wc = WordCloud(background_color='white', max_words=50)
plt.figure(figsize=(10,10))
plt.imshow(wc.generate(content))
plt.axis('off')
plt.show()

"""**Preprocessing and Cleaning**

To build the corpus from the 'content' we perfrom the following-

1. Replace any non alphabet characters with a space
2. Convert to lower case and split into words
3. Iterate over the individual words and if it is not a stopword then add the stemmed form of the word to the corpus
"""

corpus = []
stemmer = PorterStemmer()
for i in range(len(df)):
    text = re.sub('[^a-zA-Z]', ' ', df['content'].iloc[i])
    text = text.lower().split()
    text = [stemmer.stem(word) for word in text if word not in STOPWORDS]
    text = ' '.join(text)
    corpus.append(text)

"""**TF - IDF**"""

from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer(max_features=5000)
X = tfidf.fit_transform(corpus).toarray()
y = df['score']

"""**Feature Extraction**"""

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1,2),
    min_df=2,
    max_df=0.9
)
tfidf.fit(corpus)

"""**Splitting data into train and test set with 30% data with testing.**"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print(f"Shape of X_train : {X_train.shape}")
print(f"Shape of y_train : {y_train.shape}")
print(f"Shape of X_test : {X_test.shape}")
print(f"Shape of y_test : {y_test.shape}")

"""**Confusion Matrix**"""

model_dt = DecisionTreeClassifier(random_state=42)
model_dt.fit(X_train, y_train)
y_preds = model_dt.predict(X_test)
cm = confusion_matrix(y_test, y_preds)
print(cm)

cm = confusion_matrix(y_test, y_preds)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.show()

"""**Lemmatization and Tokenization**"""

nltk.download('punkt')
nltk.download('wordnet')
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
def simple_preprocess(text):
    words = word_tokenize(text)
    words = [lemmatizer.lemmatize(word) for word in words]
    return " ".join(words)

nltk.download('punkt_tab')
df['cleaned_text'] = df['content'].apply(simple_preprocess)

print(df['cleaned_text'].iloc[0])

print(df[['content', 'cleaned_text']].head())

"""**Random Forest**"""

model_rf = RandomForestClassifier(n_estimators=100, random_state=42)
model_rf.fit(X_train, y_train)

print("Training Accuracy :", model_rf.score(X_train, y_train))
print("Testing Accuracy :", model_rf.score(X_test, y_test))

"""**Decision Tree Classifier**"""

model_dt = DecisionTreeClassifier(random_state=42)
model_dt.fit(X_train, y_train)
y_preds = model_dt.predict(X_test)

print("Training Accuracy :", model_dt.score(X_train, y_train))
print("Testing Accuracy :", model_dt.score(X_test, y_test))

"""**Logistic Regression**"""

model_ds = LogisticRegression(max_iter=1000,n_jobs=-1)
model_ds.fit(X_train, y_train)
y_pred = model_ds.predict(X_test)

print("Training Accuracy :", model_ds.score(X_train, y_train))
print("Testing Accuracy :", model_ds.score(X_test, y_test))

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# Step 1: Convert text → numbers
tfidf = TfidfVectorizer(max_features=7000)
X_train_vec = tfidf.fit_transform(X_train_text)
X_test_vec = tfidf.transform(X_test_text)

# Step 2: Train model
model = LogisticRegression(max_iter=5000)
model.fit(X_train_vec, y_train)

# Step 3: Evaluate
print("Train:", model.score(X_train_vec, y_train))
print("Test :", model.score(X_test_vec, y_test))

"""**Multinomial Naive Bayes**"""

model_sf = MultinomialNB()
model_sf.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("Training Accuracy :", model_sf.score(X_train, y_train))
print("Testing Accuracy :", model_sf.score(X_test, y_test))

"""**Linear SVM**"""

model_cv = LinearSVC()
model_cv.fit(X_train, y_train)
y_pred = model_cv.predict(X_test)

print("Training Accuracy :", model_cv.score(X_train, y_train))
print("Testing Accuracy :", model_cv.score(X_test, y_test))

with open("logistic_model.pkl", "wb") as f:
    pickle.dump(model_ds, f)

with open("tfidf_vectorizer.pkl", "wb") as f:
    pickle.dump(tfidf, f)

